name: build-and-publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Ustaw nazwę repo w lowercase
        id: vars
        run: echo "REPO_LC=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - name: Logowanie do Docker Hub (cache)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Metadane obrazu (tag SHA z prefiksem scan-)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.vars.outputs.REPO_LC }}
          tags: type=sha,prefix=scan-

      - name: Buduj obraz amd64 (na potrzeby skanu)
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/weather-app:cache
          cache-to:   type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/weather-app:cache,mode=max

      - name: Skan Trivy (HIGH/CRITICAL ⇒ exit 1)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          format: table
          severity: HIGH,CRITICAL
          scanners: vuln
          ignore-unfixed: true
          exit-code: 1

  push:
    runs-on: ubuntu-latest
    needs: scan
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Ustaw nazwę repo w lowercase
        id: vars
        run: echo "REPO_LC=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - name: Logowanie do GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Logowanie do Docker Hub (cache)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Metadane obrazu (latest / semver / sha)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.vars.outputs.REPO_LC }}

      - name: Buduj i publikuj multi-arch (amd64 + arm64)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/weather-app:cache
          cache-to:   type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/weather-app:cache,mode=max